### ISSUE TITLE
Failed to follow user (button did not change state) Logic

### ISSUE THREAD

**Issue by DoubleUltera** [mifi/instauto#33]
Hi,

I noticed that whenever instauto gets the _Failed to follow user (button did not change state)_ error it continues to: 

1. Like photos of that user which then results to an error, and
2. The user gets appended to followed.json although it was not successfully followed.

Also, I think it would be more appropriate for the bot to sleep because I think the _Failed to follow user (button did not change state)_ is caused by stricter bot detection logic. Just a suggestion though.

Thanks!
![Noname](https://user-images.githubusercontent.com/29980671/97411710-97793500-193b-11eb-8ee6-8e3001745c6a.jpg)

**Comment by AlexSade** [comment]
I have the same problem

![Captura de pantalla 2020-11-05 a las 22 36 11](https://user-images.githubusercontent.com/65304609/98299209-9db08680-1fb7-11eb-8496-fbc60771ec13.png)

**Comment by mifi** [comment]
@DoubleUltera I agree we could probably sleep. The reason why followed.json gets updated is because I didn't want the bot to get stuck trying the same user over and over again in case there is an issue with following  that user.

@AlexSade try to delete cookies and start over. Also make sure you're actively using the mobile app on the same wifi / public IP as your bot for a few days.

**Comment by mifi** [comment]
Is this  still a problem?

Have added `failed: true` to the logged followed.json entry if failed.

**Comment by DoubleUltera** [comment]
This is already fixed since the update. Closing. 

Thank you.
